import type {
  GetStaticProps,
  GetServerSideProps,
  InferGetStaticPropsType,
} from "next";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation, Trans } from "next-i18next";

import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

interface Props {}

const Home = () => {
  const { t } = useTranslation("common");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1 className="text-3xl font-bold underline text-red-500">
            Hello world!
          </h1>
          <p>{t("welcome")}</p>
        </div>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<Props> = async ({
  locale,
}) => ({
  props: {
    ...(await serverSideTranslations(locale ?? "en-US", ["common", "footer"])),
  },
});

export default Home;
